import Head from 'next/head'
import Image from 'next/image'
import css from '../styles/Index.module.scss'

export default function Home() {
  return (
    <div className={css.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>bienvenue sur le blog</h1>
      </div>

    
    </div>
  )
}
